version: '3'

services: 
  server:
    container_name: server
    build: ./backend
    ports:
      - '8080:8080'
    networks:
      - mynet

  client:
    container_name: client
    build: ./frontend
    depends_on: 
      - server
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

